[project]
name = "video-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "google-generativeai==0.3.1",
    "gradio>=5.49.1",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.1",
]
